### ISSUE TITLE
Incorrect unit labels in IFT and GNOM windows

### ISSUE THREAD

**Issue by rgillilan** [jbhopkins/bioxtasraw#1]
When q units are changed from A-1 to nm-1 in the Radial Averaging panel, the old units of (A) still appear in the column labels of both the BIFT and GNOM windows. In other places, I think unit labels have simply been removed elsewhere, so that's a quick fix to avoid confusion. Longer term, probably plots should have unit labels.

**Comment by jbhopkins** [comment]
I would be in favor of removing unit labels, but not in favor of adding them everyone in a dynamic fashion. There's really no guarantee that people will work in the units set by the radial averaging panel (unless you're using RAW to reduce data I don't think anyone looks at that panel), and RAW attempts to be unit agnostic, generally. People could even be working with two datasets in different units.

**Comment by rgillilan** [comment]
I agree. If people want to use snapshots of panels in publications, they'll have to be sure to manually label or mention units. So leaving the labels out makes the most sense to actually avoid confusion.


On Sep 18, 2022, at 9:41 AM, jbhopkins ***@***.******@***.***>> wrote:



I would be in favor of removing unit labels, but not in favor of adding them everyone in a dynamic fashion. There's really no guarantee that people will work in the units set by the radial averaging panel (unless you're using RAW to reduce data I don't think anyone looks at that panel), and RAW attempts to be unit agnostic, generally. People could even be working with two datasets in different units.
