### ISSUE TITLE
UnboundLocalError in SECM.py in averageFrame method

### ISSUE THREAD

**Issue by antoniocalio95** [jbhopkins/bioxtasraw#5]
Here's the traceback:

```
Traceback (most recent call last):

  File ~\AppData\Local\Programs\Python\Python311\Lib\site-packages\spyder_kernels\py3compat.py:356 in compat_exec
    exec(code, globals, locals)

  File c:\users\anton\desktop\dio\h5read.py:104
    avg_buff, success, error = series.averageFrames(buff_range, 'sub', 'CorMap', 0.01, 'Bonferroni', forced = True)

  File ~\AppData\Local\Programs\Python\Python311\Lib\site-packages\bioxtasraw\SECM.py:1528 in averageFrames
    avg_list = sasm_list

UnboundLocalError: cannot access local variable 'sasm_list' where it is not associated with a value
```

Basically sasm_list is only defined in the case of an unsubtracted series at line 1485:

```python
if series_type == 'unsub':
        sasm_list = [self._sasm_list[idx] for idx in frame_idx]
```

I quickly fixed it by adding this to handle my case:

```python

elif series_type == 'sub':
        sasm_list = [self.subtracted_sasm_list[idx] for idx in frame_idx]
```

Although maybe you want to fix it properly to handle all possible cases.
Also, the parameters' default values for this method aren't set as they are described in the documentation, but that's also an easy fix.

**Comment by jbhopkins** [comment]
Thanks for the bug report. I've just pushed a new commit to the git that should fix this, as well as fixing the documentation mismatch though that won't be updated on the website until I make that update. If you can test it and let me know if it works for you that would be great.

**Comment by antoniocalio95** [comment]
I just tested it with the new SECM.py and I can confirm that it works as intended now, thank you very much!

**Comment by jbhopkins** [comment]
Great, glad that fixed it! Let me know if you find other issues.
