### ISSUE TITLE
request for new version release

### ISSUE THREAD

**Issue by dsclassen** [jbhopkins/bioxtasraw#6]
When building a docker image and and installing BioXTAS from pre-downloaded 2.2.2.zip file I have this problem:

```python
Python 3.10.13 | packaged by conda-forge | (main, Oct 26 2023, 17:57:40) [GCC 12.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import bioxtasraw.RAWAPI as raw
WARNING:silx.opencl.common:The module pyOpenCL has been imported but can't be used here
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/miniforge3/lib/python3.10/site-packages/bioxtasraw/RAWAPI.py", line 63, in <module>
    import bioxtasraw.DENSS as DENSS
  File "/miniforge3/lib/python3.10/site-packages/bioxtasraw/DENSS.py", line 62, in <module>
    import bioxtasraw.denss_resources.resources as resources
ModuleNotFoundError: No module named 'bioxtasraw.denss_resources'
>>> 
```

When building a docker image and installing BioXTAS from main things are working...

```bash
Python 3.10.13 | packaged by conda-forge | (main, Oct 26 2023, 17:57:40) [GCC 12.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import bioxtasraw.RAWAPI as raw
WARNING:silx.opencl.common:The module pyOpenCL has been imported but can't be used here
```

However, because of the large size of the repo I sometimes run into problems cloning during a docker build. Would you mind cutting a new release from main? 

thanks

**Comment by dsclassen** [comment]
Is:

`https://github.com/jbhopkins/bioxtasraw/archive/refs/tags/v2.2.2.zip`

the same as:

`https://sourceforge.net/projects/bioxtasraw/files/RAW-2.2.2-source.zip/download`

**Comment by jbhopkins** [comment]
Why not just grab a predownloaded zip of the current main branch? On the main page if you click the green code button, at the bottom of the menu that appears you'll see an option to download a zip, which is going to be the most update version. Alternatively you could use the git export function to generate a zip from a version of the git you have checked out.
<img width="922" alt="Screenshot 2024-03-05 at 4 11 30 PM" src="https://github.com/jbhopkins/bioxtasraw/assets/23534688/2c00dd31-5b68-4ab2-a4fe-b884f3136143">

In regards to the request for a new version, unfortunately it takes me several days (sometimes a week) to do all the necessary test, build the pre-built installers, update the documentation, etc. for a new version release and I don't have the time to do that now. I'd recommend grabbing the zip of the main branch as described above. If that doesn't work for you, let me know and we can figure out another solution.

As to your question about the zip files, probably? Sourceforge hosts the official released versions. Anything on github is autogenerated when I make a tag. They're probably the same, but you should default to using the sourceforge one.

**Comment by dsclassen** [comment]
I don't mean to make more work for you. I will try the "Download ZIP" option. I hadn't noticed that before.
